### ISSUE TITLE
handle socket error conditions

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/vpn-daemon#15]
they are now ignored... not good :-)

**Comment by auamod** [comment]
Fixed.
https://github.com/letsconnectvpn/vpn-daemon/pull/34/commits/c126a8f86f696db0446143ab8e5a9ce5f95dbae7 in https://github.com/letsconnectvpn/vpn-daemon/pull/34

**Comment by fkooman** [comment]
Also done!
