### ISSUE TITLE
add error handling when reading string

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/vpn-daemon#31]
https://github.com/letsconnectvpn/lc-daemon/blob/cc09c3702b89946e4646a14fdea18d45fdae66ae/lc-daemon/main.go#L80

This goes bad if the clients leaves without issuing the QUIT command.

**Comment by fkooman** [comment]
There are many more places where strings are read from buffers. Have error checking there too!

**Comment by auamod** [comment]
Fixed.
https://github.com/letsconnectvpn/vpn-daemon/pull/34/commits/abaa28156c274ecdf14ba73972ed02d2a9120db8 in https://github.com/letsconnectvpn/vpn-daemon/pull/34

**Comment by fkooman** [comment]
Done!
