### ISSUE TITLE
Log TLS connection info?

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/vpn-daemon#38]
Would it be easy to write some TLS connection info to stdout? E,g, the used TLS protocol and ciphersuite? Maybe there are other parameters that can be interesting to log...

**Comment by auamod** [comment]
This is possible, but maybe not as informative as you thought.
The cipher suites and versions are returned as uints.
https://golang.org/pkg/crypto/tls/#ConnectionState

So when trying to show the information only the numbers are returned.

This feature might be realized when GO1.14 is released(if its supported):
https://github.com/golang/go/issues/30325#issuecomment-537236358

**Comment by fkooman** [comment]
Not important for now.
