### ISSUE TITLE
sometimes IP from `status 2` is empty string

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/vpn-daemon#53]
```
#!/bin/sh
rm output_log.txt
while true
do
	echo "GO..."
	for i in 11940 11941 11942 11943 11945 11945 11946 11947
	do
		echo "status 2" | nc localhost ${i} | grep ^CLIENT_LIST >> output_log.txt
	done
 	sleep 5
done
```
There's quite a variety in different ways OpenVPN can return `status 2` info. The CN can be "UNDEF" or the IPs can be empty string.

For example:
```
CLIENT_LIST,UNDEF,84.Z.Y.X:55675,,,0,0,Wed Apr  8 11:21:56 2020,1586344916,UNDEF,651,0
```
Or: 
```
CLIENT_LIST,759ee01a8a1242e0cbb69aac86zzzzz,2a02:a:b:0:c:d:e:f,,,4043,3673,Wed Apr  8 11:17:40 2020,1586344660,UNDEF,4441,10
```

Until now we only ignored entries where CN=UNDEF, we should also ignore lines where the IP address(es) are the empty string, with or without CN=UNDEF.

So this occurs during connect when the connection is slow, and/or not fully established yet, probably a race condition...

**Comment by ghost** [comment]
Fixed in 1.0.1.
